# Generated by Django 4.2.10 on 2024-02-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_name', models.CharField(max_length=100, verbose_name='Имя специалиста')),
                ('expert_special', models.CharField(max_length=250, verbose_name='Специализация')),
                ('expert_logo', models.ImageField(upload_to='static/images/expert', verbose_name='Фото спеца')),
                ('expert_text', models.TextField(verbose_name='Текст описания')),
                ('tel', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('whatsapp', models.CharField(max_length=11, verbose_name='Whatsapp')),
                ('viber', models.CharField(max_length=11, verbose_name='Viber')),
                ('instagram', models.CharField(max_length=250, verbose_name='insta')),
                ('TikTok', models.CharField(max_length=250, verbose_name='TikTok')),
                ('disable_expert', models.BooleanField(verbose_name='Отключить специалиста')),
            ],
            options={
                'verbose_name': 'Специалиста',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_city', models.EmailField(max_length=100, verbose_name='e-mail')),
                ('adress_city', models.CharField(max_length=120, verbose_name='Адрес')),
                ('disable_maps', models.BooleanField(verbose_name='Отключить блок')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Секция "Footer"',
            },
        ),
        migrations.CreateModel(
            name='HowToDoIt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h4_Block', models.CharField(max_length=250, verbose_name='Заголовок блока')),
                ('h4_step1', models.CharField(max_length=50, verbose_name='h4 блока ШАГ 1')),
                ('h4_step2', models.CharField(max_length=50, verbose_name='h4 блока ШАГ 2')),
                ('h4_step3', models.CharField(max_length=50, verbose_name='h4 блока ШАГ 3')),
                ('step_1_text', models.CharField(max_length=250, verbose_name='Шаг 1 текст')),
                ('step_2_text', models.CharField(max_length=250, verbose_name='Шаг 2 текст')),
                ('step_3_text', models.CharField(max_length=250, verbose_name='Шаг 3 текст')),
                ('disable_blok', models.BooleanField(verbose_name='Отключить блок')),
            ],
            options={
                'verbose_name': 'Схема работы',
                'verbose_name_plural': 'Секция "Схема работы"',
            },
        ),
        migrations.CreateModel(
            name='ListReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reviews', models.CharField(max_length=50, verbose_name='Имя')),
                ('expert_logo', models.ImageField(upload_to="{% static 'images/reviews' %}", verbose_name='Аватарка')),
                ('text_reviews', models.CharField(max_length=300, verbose_name='Отзыв')),
                ('event_reviews', models.CharField(max_length=100, verbose_name='Событие')),
                ('disable_reviews', models.BooleanField(verbose_name='Отключить отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ListVideoReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_slide', models.CharField(max_length=1, verbose_name='Порядковый номер')),
                ('src_slide', models.CharField(max_length=300, verbose_name='Ссылка на видео')),
                ('active_slide', models.BooleanField(verbose_name='Показывать первым')),
                ('disable_slide', models.BooleanField(verbose_name='Убрать из подборки')),
            ],
            options={
                'verbose_name': 'Видео отзыв',
                'verbose_name_plural': 'Видео отзывы',
            },
        ),
        migrations.CreateModel(
            name='ListVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_frame', models.CharField(max_length=200, verbose_name='Наименование для админки')),
                ('src_frame', models.CharField(max_length=500, verbose_name='Ссылка на видео')),
                ('width_frame', models.CharField(max_length=300, verbose_name='Ширина фрейма')),
                ('height_frame', models.CharField(max_length=50, verbose_name='Высота фрейма')),
                ('disable_frame', models.BooleanField(verbose_name='Убрать из подборки(отключить)')),
                ('description_frame', models.CharField(max_length=300, verbose_name='Описание к видео')),
            ],
            options={
                'verbose_name': 'Ролик',
                'verbose_name_plural': 'Интересные Видео (Ролики)',
            },
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3_header', models.CharField(max_length=30, verbose_name='Заголовок блока')),
                ('city_name', models.CharField(max_length=30, verbose_name='Город')),
                ('city_href', models.CharField(max_length=250, verbose_name='Сссылка на город')),
                ('adress_name', models.CharField(max_length=120, verbose_name='Адрес')),
                ('adress_text', models.CharField(max_length=250, verbose_name='Сссылка на адрес')),
                ('iframe_code', models.TextField(verbose_name='Код iframe')),
                ('disable_maps', models.BooleanField(verbose_name='Отключить блок')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Секция "Карты"',
            },
        ),
        migrations.CreateModel(
            name='MenuNavHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('item_href', models.CharField(max_length=300, verbose_name='Атрибут HREF')),
                ('alt_item', models.CharField(max_length=50, verbose_name='Атрибут ALT')),
                ('disable_item', models.BooleanField(verbose_name='Отключить блок')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Основное меню (NavBar)',
            },
        ),
        migrations.CreateModel(
            name='ParametersReviewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3_header', models.CharField(max_length=250, verbose_name='Заголовок блока')),
                ('description_text', models.TextField(verbose_name='Описание блока')),
                ('disable_reviews', models.BooleanField(verbose_name='Отключить отзывы полностью')),
            ],
            options={
                'verbose_name': 'Настроить секцию',
                'verbose_name_plural': 'Секция "Отзывы" основные настройки',
            },
        ),
        migrations.CreateModel(
            name='ParametersVideosBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h4_block_header', models.CharField(max_length=250, verbose_name='Заголовок блока')),
                ('h5_text_block', models.TextField(verbose_name='Текст блока')),
                ('disable_videos', models.BooleanField(verbose_name='Отключить блок')),
            ],
            options={
                'verbose_name': 'Интересное видео',
                'verbose_name_plural': 'Секция "Интересные Видео"',
            },
        ),
        migrations.CreateModel(
            name='SeoHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description_site', models.CharField(max_length=160, verbose_name='Description')),
                ('h1_text_1', models.CharField(max_length=100, verbose_name='Первый заголовок h1')),
                ('h1_text_2', models.CharField(max_length=100, verbose_name='Второй заголовок h1')),
                ('h2_text', models.CharField(max_length=100, verbose_name='h2 заголовок')),
                ('text_button', models.CharField(max_length=30, verbose_name='Текст кнопки')),
                ('href_text', models.CharField(max_length=30, verbose_name='Текст ссылки')),
                ('favicon', models.ImageField(upload_to='static/images', verbose_name='FAV иконка')),
                ('logo_main', models.ImageField(upload_to='static/images', verbose_name='Логотип сайта')),
            ],
            options={
                'verbose_name': 'Основные параметры сайта',
                'verbose_name_plural': 'SEO настройки',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3_block_header', models.CharField(max_length=250, verbose_name='Заголовок блока')),
                ('h4_text_block', models.TextField(verbose_name='Текст блока')),
                ('disable_service', models.BooleanField(verbose_name='Отключить блок')),
            ],
            options={
                'verbose_name': 'Наши услуги',
                'verbose_name_plural': 'Секция "Наши услуги"',
            },
        ),
    ]
